Flowpack:
  SchemaOrg:
    NodeTypes:
      renderedNodeTypeRootPath: '%FLOW_PATH_DATA%NodeTypes/Configuration/'

      defaultPackageKey: 'Flowpack.SchemaOrg.NodeTypes'

      schemas:
        jsonFilename: 'resource://Flowpack.SchemaOrg.NodeTypes/Private/Schema/All.json'

      nodeTypeMapping:
        ImageObject: 'TYPO3.Neos.NodeTypes:Image'

      propertyBlackList:
        # todo: add support for relation to an other Document
        'sameAs': TRUE
        # Need to be defined in TypoScript / Fluid, logic based
        'url': TRUE
        'breadcrumb': TRUE
        'wordCount': TRUE
        'aggregateRating': TRUE
        'interactionCount': TRUE

      # By default the parser create abstract node, this can be change here
      typeDefaultConfiguration:
        '*':
          abstract: TRUE
          nodeLabelGenerator: 'Flowpack\SchemaOrg\NodeTypes\Domain\Model\DefaultNodeLabelGenerator'
          ui:
            icon: 'icon-gear'

        'Review':
          abstract: FALSE
          superTypes:
            - 'TYPO3.Neos.NodeTypes:Page'

        'PostalAddress':
          ui:
            icon: 'icon-building'

        'GeoCoordinates':
          ui:
            icon: 'icon-map-marker'

        'OpeningHoursSpecification':
          ui:
            icon: 'icon-time'

        'Event':
          abstract: FALSE
          superTypes:
            - 'TYPO3.Neos.NodeTypes:Page'

        'Place':
          abstract: FALSE
          superTypes:
            - 'TYPO3.Neos:Content'

        'VideoObject':
          abstract: FALSE
          superTypes:
            - 'TYPO3.Neos:Content'


      propertyMixinsMapping:
        'image':
          - 'TYPO3.Neos.NodeTypes:ImageMixin'
          - 'TYPO3.Neos.NodeTypes:ImageCaptionMixin'

        'description':
          - 'Flowpack.SchemaOrg.NodeTypes:DescriptionMixin'

        'articleBody':
          - 'Flowpack.SchemaOrg.NodeTypes:ArticleBodyMixin'

        'comment':
          - 'Flowpack.SchemaOrg.NodeTypes:CommentMixin'

#        'address':
#          - 'Flowpack.SchemaOrg.NodeTypes:AdressMixin'

#        'location':
#          - 'Flowpack.SchemaOrg.NodeTypes:LocationMixin'

#        'geo':
#          - 'Flowpack.SchemaOrg.NodeTypes:GeoMixin'

#        'openingHoursSpecification':
#          - 'Flowpack.SchemaOrg.NodeTypes:OpeningHoursSpecificationMixin'

        'photo':
          - 'Flowpack.SchemaOrg.NodeTypes:PhotoMixin'

        'photos':
          - 'Flowpack.SchemaOrg.NodeTypes:PhotosMixin'

      propertyDefaultConfiguration:
        '*':
          ui:
            reloadIfChanged: TRUE

        'email':
          type: 'string'
          validation:
            validation:
              'TYPO3.Neos/Validation/EmailAddressValidator': []

        'logo':
          type: TYPO3\Media\Domain\Model\ImageInterface
          ui:
            label: 'Image'

        'proficiencyLevel':
          ui:
            inspector:
              editor: 'TYPO3.Neos/Inspector/Editors/SelectBoxEditor'
              editorOptions:
                values:
                  '':
                    label: ''
                  'beginner':
                    label: 'Beginner'
                  'expert':
                    label: 'Expert'

        # @see http://www.w3.org/wiki/WebSchemas/Accessibility
        'accessibilityAPI':
          ui:
            inspector:
              editor: 'TYPO3.Neos/Inspector/Editors/SelectBoxEditor'
              editorOptions:
                values:
                  '':
                    label: ''
                  'AndroidAccessibility':
                    label: 'AndroidAccessibility'
                  'ARIA':
                    label: 'ARIA'
                  'ATK':
                    label: 'ATK'
                  'AT-SPI':
                    label: 'AT-SPI'
                  'BlackberryAccessibility':
                    label: 'BlackberryAccessibility'
                  'iAccessible2':
                    label: 'iAccessible2'
                  'iOSAccessibility':
                    label: 'iOSAccessibility'
                  'JavaAccessibility':
                    label: 'JavaAccessibility'
                  'MacOSXAccessibility':
                    label: 'MacOSXAccessibility'
                  'MSAA':
                    label: 'MSAA'
                  'UIAutomation':
                    label: 'UIAutomation'

        # @see http://www.w3.org/wiki/WebSchemas/Accessibility
        'accessibilityControl':
          ui:
            inspector:
              editor: 'TYPO3.Neos/Inspector/Editors/SelectBoxEditor'
              editorOptions:
                values:
                  '':
                    label: ''
                  'fullKeyboardControl':
                    label: 'fullKeyboardControl'
                  'fullMouseControl':
                    label: 'fullMouseControl'
                  'fullSwitchControl':
                    label: 'fullSwitchControl'
                  'fullTouchControl':
                    label: 'fullTouchControl'
                  'fullVideoControl':
                    label: 'fullVideoControl'
                  'fullVoiceControl':
                    label: 'fullVoiceControl'

        # @see http://www.w3.org/wiki/WebSchemas/Accessibility
        'accessibilityFeature':
          ui:
            inspector:
              editor: 'TYPO3.Neos/Inspector/Editors/SelectBoxEditor'
              editorOptions:
                values:
                  '':
                    label: ''
                  'alternativeText':
                    label: 'alternativeText'
                  'annotations':
                    label: 'annotations'
                  'audioDescription':
                    label: 'audioDescription'
                  'bookmarks':
                    label: 'bookmarks'
                  'braille':
                    label: 'braille'
                  'captions':
                    label: 'captions'
                  'ChemML':
                    label: 'ChemML'
                  'describedMath':
                    label: 'describedMath'
                  'displayTransformability':
                    label: 'displayTransformability'
                  'highContrastAudio':
                    label: 'highContrastAudio'
                  'highContrastDisplay':
                    label: 'highContrastDisplay'
                  'index':
                    label: 'index'
                  'largePrint':
                    label: 'largePrint'
                  'latex':
                    label: 'latex'
                  'longDescription':
                    label: 'longDescription'
                  'MathML':
                    label: 'MathML'
                  'none':
                    label: 'none'
                  'printPageNumbers':
                    label: 'printPageNumbers'
                  'readingOrder':
                    label: 'readingOrder'
                  'signLanguage':
                    label: 'signLanguage'
                  'structuralNavigation':
                    label: 'structuralNavigation'
                  'tableOfContents':
                    label: 'tableOfContents'
                  'taggedPDF':
                    label: 'taggedPDF'
                  'tactileGraphic':
                    label: 'tactileGraphic'
                  'tactileObject':
                    label: 'tactileObject'
                  'timingControl':
                    label: 'timingControl'
                  'transcript':
                    label: 'transcript'
                  'ttsMarkup':
                    label: 'ttsMarkup'
                  'unlocked':
                    label: 'unlocked'

        # @see http://www.w3.org/wiki/WebSchemas/Accessibility
        'accessibilityHazard':
          ui:
            inspector:
              editor: 'TYPO3.Neos/Inspector/Editors/SelectBoxEditor'
              editorOptions:
                values:
                  '':
                    label: ''
                  'flashing':
                    label: 'flashing'
                  'noFlashingHazard':
                    label: 'noFlashingHazard'
                  'motionSimulation':
                    label: 'motionSimulation'
                  'noMotionSimulationHazard':
                    label: 'noMotionSimulationHazard'
                  'sound':
                    label: 'sound'
                  'noSoundHazard':
                    label: 'noSoundHazard'

        'educationalUse':
          ui:
            inspector:
              editor: 'TYPO3.Neos/Inspector/Editors/SelectBoxEditor'
              editorOptions:
                values:
                  '':
                    label: ''
                  'assignment':
                    label: 'assignment'
                  'group work':
                    label: 'group work'

        'interactivityType':
          ui:
            inspector:
              editor: 'TYPO3.Neos/Inspector/Editors/SelectBoxEditor'
              editorOptions:
                values:
                  '':
                    label: ''
                  'active':
                    label: 'active'
                  'expositive':
                    label: 'expositive'
                  'mixed':
                    label: 'mixed'

        'associatedMedia':
          type: array<TYPO3\Media\Domain\Model\Asset>
